config/routes.rb
Rails.application.routes.draw do
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/checkout", to: "orders#new", as: "checkout"
  post "/checkout", to: "orders#create"
  get "/cart", to: "carts#show"
  patch "/edit_name/:id", to: "users#edit_name", as: "edit_name"

  resources :users
  resources :cartitems
  resources :carts
  resources :shopper, only: [:index, :show]
  resources :products
  resources :orders, only: [:new, :create, :show, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  root("shopper#index", as: "shopperindex") #shopperindex_path

end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  before_action :set_cart
  before_action :set_cartitem, only: %i[ show edit update destroy ]

  # GET /cartitems
  def index
    @cartitems = Cartitem.all
  end

  def show
  end

  def new
    @cartitem = Cartitem.new
  end

  def edit
  end

  def create
    product = Product.find_by(id: params[:product_id])
    unless product
      return redirect_to shopper_index_path, alert: "Product not found."
    end
  
    if product.quantity <= 0 || !product.available
      return redirect_to shopper_index_path, alert: "Sorry, this item is not available now."
    end
  
    exist_item = @cart.cartitems.find_by(product_id: product.id)
  
    if exist_item
      if exist_item.quantity >= product.quantity
        return redirect_to shopper_index_path, alert: "Add to cart failed: stock limit reached."
      end
      exist_item.quantity += 1
      if exist_item.save
        redirect_to shopper_index_path(added: product.id)
      else
        redirect_to shopper_index_path, alert: "Failed to add item."
      end
    else
      @cartitem = @cart.cartitems.build(product_id: product.id, quantity: 1)
  
      if @cartitem.save
        redirect_to shopper_index_path(added: product.id)
      else
        redirect_to shopper_index_path, alert: "Failed to add item."
      end
    end
  end


  def update
    product = @cartitem.product
    new_qty = params[:cartitem][:quantity].to_i
    
    if new_qty > product.quantity
      respond_to do |format|
        format.js { flash.now[:alert] = "Not enough stock. Maximum availble is #{product.quantity}." }
        format.html { redirect_to cart_path, alert: "Not enough stock. Maximum availble is #{product.quantity}." }
      end
      return
    end

    if @cartitem.update(cartitem_params)
      respond_to do |format|
        format.js
        format.html { redirect_to cart_path }
      end
    else
      respond_to do |format|
        format.js
        format.html { render :edit }
      end
    end
  end

  def destroy
    @cartitem.destroy!
    redirect_to cart_path(session[:cart_id]), notice: "Item removed."
  end

  private

  def set_cart
    @cart = current_cart
  end

  def set_cartitem
    @cartitem = Cartitem.find(params[:id])
  end

  def cartitem_params
    params.require(:cartitem).permit(:quantity)
  end
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/views/cartitems/_cartitem.html.erb
<div id="<%= dom_id(cartitem) %>" 
     style="display:flex; align-items:center; flex-wrap:nowrap; gap:25px; margin:12px 0; min-width:650px;">

  <div style="flex:0 0 auto;">
    <%= image_tag cartitem.product.image,
        style:"width:100px; border:0.5px solid beige; background:white;" %>
  </div>

  <div style="flex:1; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">
    <strong><%= cartitem.product.name %></strong>
  </div>

  <div style="flex:0 0 70px;">
    <%= form_with model: cartitem, url: cartitem_path(cartitem), method: :patch, remote: true do |f| %>
      <%= f.select :quantity, (1..15).to_a,
          { selected: cartitem.quantity },
          { onchange: "this.form.submit()", style: "padding:3px; width:60px;" } %>
    <% end %>
  </div>

  <div style="flex:0 0 auto;">
    <%= button_to "Remove",
    cartitem_path(cartitem),
    method: :delete,
    form: { data: { turbo_stream: true } },
    class: "remove-btn",
    style: "color:red; cursor:pointer; background:none; border:none;" %>
  </div>

  <div style="flex:0 0 60px; text-align:right;">
    $<%= cartitem.product.price %>
  </div>

</div>

app/views/cartitems/_form.html.erb
<%= form_with(model: cartitem) do |form| %>
  <% if cartitem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cartitem.errors.count, "error") %> prohibited this cartitem from being saved:</h2>

      <ul>
        <% cartitem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cartitems/_order_summary.html.erb
<div style="padding:10px;">
    <hr>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">

        <span>Subtotal</span>
        <span style="text-align:right;">$<%= cart.subtotal %></span>
    </div>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
        <span>Delivery Fee</span>
        <span style="text-align:right;">$<%= cart.delivery_fee %></span>
    </div>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
        <span>Estimated Sales Tax</span>
        <span style="text-align:right;">$<%= cart.estimated_tax %></span>
    </div>
    <hr>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
        <strong>Total</strong>
        <strong style="text-align:right;">$<%= cart.total %></strong>
    </div>
</div>

app/views/cartitems/edit.html.erb
<h1>Editing cartitem</h1>

<%= render "form", cartitem: @cartitem %>

<br>

<div>
  <%= link_to "Show this cartitem", @cartitem %> |
  <%= link_to "Back to cartitems", cartitems_path %>
</div>

app/views/cartitems/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cartitems</h1>

<div id="cartitems">
  <% @cartitems.each do |cartitem| %>
    <%= render cartitem %>
    <p>
      <%= link_to "Show this cartitem", cartitem %>
    </p>
  <% end %>
</div>

<%= link_to "New cartitem", new_cartitem_path %>

app/views/cartitems/new.html.erb
<h1>New cartitem</h1>

<%= render "form", cartitem: @cartitem %>

<br>

<div>
  <%= link_to "Back to cartitems", cartitems_path %>
</div>

app/views/cartitems/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cartitem %>

<div>
  <%= link_to "Edit this cartitem", edit_cartitem_path(@cartitem) %> |
  <%= link_to "Back to cartitems", cartitems_path %>

  <%= button_to "Destroy this cartitem", @cartitem, method: :delete %>
</div>

app/views/cartitems/update.js.erb
# document.querySelector("#item-<%= @cartitem.id %>-subtotal").innerHTML =
#   "<%= j number_to_currency(@cartitem.subtotal) %>";

# document.querySelector("#cart-total").innerHTML =
# "<%= j number_to_currency(@cart.total) %>";

document.getElementById("order_summary").innerHTML =
  "<%= j(render partial: 'cartitems/order_summary', locals: { cart: @cart }) %>";