config/routes.rb
Rails.application.routes.draw do
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/checkout", to: "orders#new", as: "checkout"
  post "/checkout", to: "orders#create"
  get "/cart", to: "carts#show"
  patch "/edit_name/:id", to: "users#edit_name", as: "edit_name"

  resources :users
  resources :cartitems
  resources :carts
  resources :shopper, only: [:index, :show]
  resources :products
  resources :orders, only: [:new, :create, :show, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  root("shopper#index", as: "shopperindex") #shopperindex_path

end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_secure_password
  validates :email, uniqueness: true

  attr_accessor :card_number  


  def admin?
    role == "admin"
  end
  
  def shopper?
    role == "shopper"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy edit_name ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @fullname = @user.first_name + @user.last_name
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def edit_name
    if @user.update(name_params)
      redirect_to @user, notice: "User name updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to shopper_index_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if params[:user][:card_number].present?
      num = params[:user][:card_number].gsub(/\D/, "")
      @user.card_last4digits = num[-4..]
      @user.pay_type = "credit card"
    end
  
    if @user.update(user_params)
      redirect_to params[:return_to] || user_path(@user), notice: "Profile updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to shopper_index_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit( :first_name, :last_name, :email, :password, :password_confirmation, :address, :pay_type, :phone)
    end

    def name_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editform.html.erb
<%= form_with(model: @user) do |form| %>
    <% if @user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div>
    <%= form.label :first_name, "First Name", style: "display: block" %>
    <%= form.text_field :first_name %>
    </div>

    <div>
    <%= form.label :last_name, "Last Name", style: "display: block" %>
    <%= form.text_field :last_name %>
    </div>

    <div>
    <%= form.label :password, "Password", style: "display: block" %>
    <%= form.password_field :password %>
    </div>

    <div>
    <%= form.label :password_confirmation, "Confirm Password", style: "display: block" %>
    <%= form.password_field :password_confirmation %>
    </div>

    <div>
    <%= form.label :email, "Email Address", style: "display: block" %>
    <%= form.text_field :email %>
    </div>

    <div>
    <%= form.label :phone, "Phone Number", style: "display: block" %>
    <%= form.text_field :phone %>
    </div>
    
    <div>
      <%= form.label :delivery_address, "Delivery Address", style: "display: block" %>
      <%= form.text_area :address %>
    </div>
  
    <div>
      <%= form.label :pay_type, "Pay Type", style: "display: block" %>
      <%= form.select :pay_type, ["credit card", "debit card", "PayPal"], { prompt: "Select a payment method" }%>
    </div>
  

  
    <div>
        <%= form.label :card_number, "Card Number", style: "display: block" %>
        <%= form.text_field :card_number, autocomplete:"off" %>
    </div>
    <br>
    <div>
      <%= form.submit "Save change" %>
    </div>
  <% end %>
  

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, "First Name", style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, "Last Name", style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :password, "Password", style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, "Confirm Password", style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :email, "Email Address", style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Pay_type:</strong>
    <%= user.pay_type %>
  </p>
  <hr>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>
<%= hidden_field_tag :return_to, user_path(@user) %>
<h1>Editing your profile</h1>

<%= render "editform", user: @user %>

<br>

<div>
  <%= link_to "Back", user_path %>
</div>

app/views/users/edit_name.html.erb
<%= form_with model: @user, url: edit_name_path(@user), method: :patch do |f| %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
  
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  
    <%= f.submit "Save" %>
<% end %>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h2>Login & Security</h2>

  <p>
    <strong>Name:</strong>
    <%= @fullname%>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <p>
    <strong>Phone number:</strong>
    <%= @user.phone %>
  </p>
  <p>
    <strong>Password:</strong>
    **********
  </p>

<h2>Delivery Address</h2>
  <% if @user.address.nil?%>
   
  <% else %>
    <p>
      <strong>Address:</strong>
      <%= @user.address %>
    </p>
  <% end %>


<h2>Payment Method</h2>
  <p>
    <strong>Pay_type:</strong>
    <%= @user.pay_type %>
  </p>
  <p>
    <strong>Card Number:</strong>
    <% if @user.card_last4digits.present? %>
      **** **** **** <%= @user.card_last4digits %>
    <% end %>
  </p>


</div>


<div>
  <%= link_to "Edit your profile", edit_user_path%>
  <%= button_to "Delete your account", @user, method: :delete %>
</div>