config/routes.rb
Rails.application.routes.draw do
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/checkout", to: "orders#new", as: "checkout"
  post "/checkout", to: "orders#create"
  get "/cart", to: "carts#show"
  patch "/edit_name/:id", to: "users#edit_name", as: "edit_name"

  resources :users
  resources :cartitems
  resources :carts
  resources :shopper, only: [:index, :show]
  resources :products
  resources :orders, only: [:new, :create, :show, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  root("shopper#index", as: "shopperindex") #shopperindex_path

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Online Shop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- Bootstrap CSS -->
    <link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
  crossorigin="anonymous">

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", type: "module" %>

  </head>

  <body class="<%= controller_name %>">
   
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <% if current_user&.admin? %>
            <a class="navbar-brand" href="/products">My online shop</a>
          <% else %>
            <a class="navbar-brand" href="/shopper">My online shop</a>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              
              <% if current_user&.admin? %>
                <li class="nav-item">
                  <a class="nav-link active" href="/products/new">New Product</a>
                </li>
              <% end %>

              <% if current_user&.shopper? %>
                <li class="nav-item">
                  <%= link_to "Cart", cart_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Orders", orders_path, class: "nav-link active" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Profile", user_path(session[:user_id]), class: "nav-link active" %>
                </li>
              <% end %>

              <% if logged_in? %>
                <li style="display:flex;justify-content:flex-end;">
                  <%= link_to "Log out", logout_path, data: { turbo_method: :delete }, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item" style="display:flex;justify-content:flex-end;">
                  <a class="nav-link" href="/users/new">Sign up</a>
                </li>
                <li class="nav-item" style="display:flex;justify-content:flex-end;">
                  <a class="nav-link" href="/login">Sign in</a>
                </li>
              <% end %>              

            </ul>
          </div>
        </div>
        
      </nav>
    </header>

    <main>
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <div class="layout">
        <section>
          <%= yield %>
        </section>
      </div>
    </main>
  <!-- Bootstrap JS (required for offcanvas, modal, dropdown, etc.) -->
<script 
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
  crossorigin="anonymous">
</script>
  </body>
</html>